<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { Bot, RefreshCw, Save, Settings2 } from "lucide-vue-next";
import AiopsModuleTabs from "../components/AiopsAdminTabs.vue";
import { aiopsApi } from "../services/aiopsApi";

const loading=ref(false),saving=ref(false),error=ref(""),notice=ref(""); const qq=ref<Record<string,any>>({});
const form=reactive({platform_name:"JSCN AIOps",default_analysis_window:"24",default_refresh_interval:"30",ai_model_name:"",data_retention_days:"30",auto_refresh_enabled:"true",analysis_done_notify_enabled:"false"});
async function load(){loading.value=true;error.value="";try{const[s,q]=await Promise.all([aiopsApi<{item:Record<string,any>}>("/system/settings"),aiopsApi<{item:Record<string,any>}>("/system/qq-bot-status")]);Object.assign(form,s.item||{});qq.value=q.item||{};}catch(err){error.value=err instanceof Error?err.message:"配置加载失败";}finally{loading.value=false;}}
async function save(){saving.value=true;error.value="";try{await aiopsApi("/system/settings",{method:"PUT",body:JSON.stringify(form)});notice.value="AIOps 配置已保存";}catch(err){error.value=err instanceof Error?err.message:"配置保存失败";}finally{saving.value=false;}}
onMounted(load);
</script>

<template><div class="aiops-page" :class="{loading}"><section class="aiops-page-head"><div><span>AIOps · 系统治理</span><h1>运行参数与机器人状态</h1><p>保留 AIOps 专属运行参数；账号、角色和组织权限继续由网管系统统一维护。</p></div><button class="btn btn-secondary" @click="load"><RefreshCw :size="15"/>刷新</button></section><AiopsModuleTabs/><div v-if="error" class="aiops-notice error">{{error}}</div><div v-if="notice" class="aiops-notice success">{{notice}}</div><section class="aiops-settings-layout"><form class="card aiops-settings-card" @submit.prevent="save"><header><Settings2 :size="20"/><div><h2>AIOps 运行设置</h2><p>设置仅影响 AIOps 分析与刷新行为。</p></div></header><div class="aiops-settings-grid"><label><span>平台名称</span><input v-model="form.platform_name"/></label><label><span>默认分析窗口</span><select v-model="form.default_analysis_window"><option value="4">4 小时</option><option value="12">12 小时</option><option value="24">24 小时</option></select></label><label><span>刷新间隔（秒）</span><input v-model="form.default_refresh_interval" type="number" min="10"/></label><label><span>默认模型名称</span><input v-model="form.ai_model_name" placeholder="留空时使用用途绑定"/></label><label><span>数据保留天数</span><input v-model="form.data_retention_days" type="number" min="1"/></label><label><span>自动刷新</span><select v-model="form.auto_refresh_enabled"><option value="true">启用</option><option value="false">停用</option></select></label><label><span>分析完成通知</span><select v-model="form.analysis_done_notify_enabled"><option value="true">启用</option><option value="false">停用</option></select></label></div><footer><button class="btn btn-primary" :disabled="saving"><Save :size="14"/>{{saving?'保存中…':'保存设置'}}</button></footer></form><article class="card aiops-settings-card"><header><Bot :size="20"/><div><h2>QQ 运维机器人</h2><p>NapCat 与服务身份调用状态。</p></div><span class="aiops-state-pill" :class="qq.online?'ok':'muted'">{{qq.online?'在线':'离线'}}</span></header><dl class="aiops-settings-status"><div><dt>状态</dt><dd>{{qq.status||'unknown'}}</dd></div><div><dt>OneBot</dt><dd>{{qq.onebot_ok?'正常':'不可用'}}</dd></div><div><dt>最近上报</dt><dd>{{qq.ts||'-'}}</dd></div><div><dt>邮件提醒</dt><dd>{{qq.email_enabled?'启用':'停用'}}</dd></div><div v-if="qq.error"><dt>错误</dt><dd class="danger">{{qq.error}}</dd></div></dl><a v-if="qq.login_url" class="btn btn-secondary" :href="qq.login_url" target="_blank" rel="noopener">打开登录入口</a></article></section></div></template>
