<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { Pencil, Plus, RefreshCw, ShieldCheck, Trash2 } from "lucide-vue-next";
import AiopsModuleTabs from "../components/AiopsModuleTabs.vue";
import { aiopsApi } from "../services/aiopsApi";

type Rule = Record<string, any> & { id: number; rule_name: string; raw_text: string; enabled: boolean };
const items = ref<Rule[]>([]); const loading = ref(false); const saving = ref(false); const error = ref("");
const form = reactive({ rule_name: "", raw_text: "", priority: 100, enabled: true });
const editingId = ref<number | null>(null); const parsed = ref<Record<string, any> | null>(null);
async function load() { loading.value = true; error.value = ""; try { items.value = (await aiopsApi<{ items: Rule[] }>("/ai-analysis-rules")).items || []; } catch (err) { error.value = err instanceof Error ? err.message : "规则加载失败"; } finally { loading.value = false; } }
function edit(rule?: Rule) { editingId.value=rule?.id||null; form.rule_name=rule?.rule_name||""; form.raw_text=rule?.raw_text||""; form.priority=rule?.priority??100; form.enabled=rule?.enabled??true; parsed.value=rule?.parsed_rule||null; }
async function preview() { if(!form.raw_text.trim()) return; try { parsed.value=(await aiopsApi<{parsed_rule:Record<string,any>}>("/ai-analysis-rules/parse",{method:"POST",body:JSON.stringify({raw_text:form.raw_text})})).parsed_rule; } catch(err){error.value=err instanceof Error?err.message:"规则解析失败";} }
async function saveRule() { saving.value = true; error.value = ""; try { await aiopsApi(editingId.value?`/ai-analysis-rules/${editingId.value}`:"/ai-analysis-rules", { method: editingId.value?"PUT":"POST", body: JSON.stringify(form) }); edit(); await load(); } catch (err) { error.value = err instanceof Error ? err.message : "规则保存失败"; } finally { saving.value = false; } }
async function toggle(rule: Rule) { try { await aiopsApi(`/ai-analysis-rules/${rule.id}/toggle`, { method: "POST", body: JSON.stringify({ enabled: !rule.enabled }) }); await load(); } catch (err) { error.value = err instanceof Error ? err.message : "切换失败"; } }
async function remove(rule: Rule) { if (!window.confirm(`确认删除规则“${rule.rule_name}”？`)) return; try { await aiopsApi(`/ai-analysis-rules/${rule.id}`, { method: "DELETE" }); await load(); } catch (err) { error.value = err instanceof Error ? err.message : "删除失败"; } }
onMounted(load);
</script>

<template><div class="aiops-page" :class="{ loading }"><section class="aiops-page-head"><div><span>AIOps · 治理</span><h1>AI 分析规则</h1><p>用自然语言定义降噪、提权和报告规则；后端解析后以结构化规则安全执行。</p></div><button class="btn btn-secondary" @click="load"><RefreshCw :size="15" />刷新</button></section><AiopsModuleTabs /><div v-if="error" class="aiops-notice error">{{ error }}</div><form class="card aiops-rule-composer" @submit.prevent="saveRule"><div><ShieldCheck :size="22" /><span><strong>{{editingId?'编辑规则':'新增自然语言规则'}}</strong><small>例如：将核心机房的 BFD 反复抖动提升为高优先级，并在主报告置顶。</small></span></div><input v-model="form.rule_name" placeholder="规则名称（可选）" /><textarea v-model="form.raw_text" required placeholder="输入规则内容…" @blur="preview"></textarea><label>优先级 <input v-model.number="form.priority" type="number" min="0" max="10000" /></label><div class="aiops-editor-actions"><button type="button" class="btn btn-secondary" @click="preview">预解析</button><button class="btn btn-primary" :disabled="saving"><Plus :size="15" />{{ saving ? "保存中…" : editingId?'更新规则':'解析并保存' }}</button></div><div v-if="parsed" class="aiops-rule-preview"><strong>系统理解</strong><span>类型：{{parsed.rule_type||'-'}}</span><span>动作：{{parsed.action||'-'}}</span><span v-if="parsed.human_readable_summary">{{parsed.human_readable_summary}}</span><b v-if="parsed.requires_confirmation">需要人工确认，保存后默认停用</b></div></form><section class="aiops-admin-grid"><article v-for="rule in items" :key="rule.id" class="card aiops-admin-card aiops-rule-card"><header><span class="aiops-status-dot" :class="rule.enabled ? 'ok' : 'muted'"></span><div><h2>{{ rule.rule_name }}</h2><p>{{ rule.rule_type || "通用规则" }} · 优先级 {{ rule.priority }}</p></div><button class="aiops-switch" :class="{ active: rule.enabled }" :aria-label="rule.enabled ? '停用规则' : '启用规则'" @click="toggle(rule)"><i></i></button></header><blockquote>{{ rule.raw_text }}</blockquote><div class="aiops-tags"><span v-for="family in rule.target_event_families" :key="family">{{ family }}</span><span v-if="rule.scope">范围：{{ rule.scope }}</span></div><footer><span>命中 {{ rule.hit_count || 0 }} 次 · {{ rule.created_by || "-" }}</span><button class="btn btn-secondary" @click="edit(rule)"><Pencil :size="14"/>编辑</button><button class="btn btn-danger-ghost" @click="remove(rule)"><Trash2 :size="14" />删除</button></footer></article><div v-if="!items.length && !loading" class="card aiops-empty"><strong>尚未配置分析规则</strong></div></section></div></template>
