<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from "vue";
import { Cpu, Pencil, Plus, RefreshCw, RotateCw, Save, TestTube2, Trash2 } from "lucide-vue-next";
import AiopsModuleTabs from "../components/AiopsAdminTabs.vue";
import { aiopsApi } from "../services/aiopsApi";

type Provider = Record<string, any> & { id: number; name: string; enabled: boolean };
type Model = Record<string, any> & { id: number; model_id: string; provider_name?: string; enabled: boolean };
type Binding = Record<string, any>;
type UsageKey = { key:string; label:string };
const providers=ref<Provider[]>([]), models=ref<Model[]>([]), bindings=ref<Binding[]>([]), usageKeys=ref<UsageKey[]>([]);
const loading=ref(false), saving=ref(false), error=ref(""), notice=ref(""), busy=ref("");
const providerEditor=ref(false), providerId=ref<number|null>(null);
const providerForm=reactive({name:"",base_url:"",api_key:"",api_key_env:"",timeout_seconds:60,remark:"",enabled:true});
const modelEditor=ref(false), modelId=ref<number|null>(null);
const modelForm=reactive({provider_id:"",model_id:"",display_name:"",endpoint_type:"chat",input_types:"text",max_context_tokens:"",max_output_tokens:"",supports_tools:false,supports_streaming:false,remark:"",enabled:true});
const selectedUsage=ref("aiops_scheduled_analysis"); const bindingDraft=ref<{model_pk:string;priority:number;enabled:boolean;purpose_note:string}[]>([]);
const chatModels=computed(()=>models.value.filter(m=>m.endpoint_type==="chat"&&m.enabled));

function message(err:unknown,fallback:string){return err instanceof Error?err.message:fallback;}
async function load(){loading.value=true;error.value="";try{const[p,m,b,u]=await Promise.all([aiopsApi<{items:Provider[]}>("/llm/providers"),aiopsApi<{items:Model[]}>("/llm/models"),aiopsApi<{items:Binding[]}>("/llm/usage-bindings"),aiopsApi<{items:UsageKey[]}>("/llm/usage-keys")]);providers.value=p.items||[];models.value=m.items||[];bindings.value=b.items||[];usageKeys.value=u.items||[];syncBindings();}catch(err){error.value=message(err,"模型配置加载失败");}finally{loading.value=false;}}
function editProvider(row?:Provider){providerId.value=row?.id||null;Object.assign(providerForm,{name:row?.name||"",base_url:row?.base_url||"",api_key:"",api_key_env:row?.api_key_env||"",timeout_seconds:row?.timeout_seconds||60,remark:row?.remark||"",enabled:row?.enabled??true});providerEditor.value=true;}
async function saveProvider(){saving.value=true;try{await aiopsApi(providerId.value?`/llm/providers/${providerId.value}`:"/llm/providers",{method:providerId.value?"PUT":"POST",body:JSON.stringify(providerForm)});providerEditor.value=false;notice.value="供应商已保存";await load();}catch(err){error.value=message(err,"供应商保存失败");}finally{saving.value=false;}}
async function deleteProvider(row:Provider){if(!confirm(`删除供应商“${row.name}”及其模型？`))return;try{await aiopsApi(`/llm/providers/${row.id}`,{method:"DELETE"});await load();}catch(err){error.value=message(err,"供应商删除失败");}}
async function refreshProvider(row:Provider){busy.value=`p${row.id}`;try{await aiopsApi(`/llm/providers/${row.id}/refresh`,{method:"POST",body:"{}"});notice.value="模型目录已同步";await load();}catch(err){error.value=message(err,"模型同步失败");}finally{busy.value="";}}
function editModel(row?:Model){modelId.value=row?.id||null;Object.assign(modelForm,{provider_id:String(row?.provider_id||providers.value[0]?.id||""),model_id:row?.model_id||"",display_name:row?.display_name||"",endpoint_type:row?.endpoint_type||"chat",input_types:(row?.input_types||["text"]).join(","),max_context_tokens:row?.max_context_tokens||"",max_output_tokens:row?.max_output_tokens||"",supports_tools:row?.supports_tools||false,supports_streaming:row?.supports_streaming||false,remark:row?.remark||"",enabled:row?.enabled??true});modelEditor.value=true;}
async function saveModel(){saving.value=true;try{const payload={...modelForm,provider_id:Number(modelForm.provider_id),input_types:modelForm.input_types.split(",").map(v=>v.trim()).filter(Boolean),output_types:["text"]};await aiopsApi(modelId.value?`/llm/models/${modelId.value}`:"/llm/models",{method:modelId.value?"PUT":"POST",body:JSON.stringify(payload)});modelEditor.value=false;notice.value="模型已保存";await load();}catch(err){error.value=message(err,"模型保存失败");}finally{saving.value=false;}}
async function deleteModel(row:Model){if(!confirm(`删除模型“${row.model_id}”？`))return;try{await aiopsApi(`/llm/models/${row.id}`,{method:"DELETE"});await load();}catch(err){error.value=message(err,"模型删除失败");}}
async function testModel(row:Model){busy.value=`m${row.id}`;try{await aiopsApi(`/llm/models/${row.id}/test`,{method:"POST",body:"{}"});notice.value="模型连通测试完成";await load();}catch(err){error.value=message(err,"模型测试失败");}finally{busy.value="";}}
function syncBindings(){bindingDraft.value=bindings.value.filter(b=>b.usage_key===selectedUsage.value).map(b=>({model_pk:String(b.model_pk),priority:Number(b.priority||100),enabled:b.enabled!==false,purpose_note:b.purpose_note||""}));}
function addBinding(){const first=chatModels.value.find(m=>!bindingDraft.value.some(b=>Number(b.model_pk)===m.id));if(first)bindingDraft.value.push({model_pk:String(first.id),priority:(bindingDraft.value.length+1)*10,enabled:true,purpose_note:""});}
async function saveBindings(){saving.value=true;try{await aiopsApi(`/llm/usage-bindings/${selectedUsage.value}`,{method:"PUT",body:JSON.stringify({items:bindingDraft.value})});notice.value="用途绑定已保存";await load();}catch(err){error.value=message(err,"用途绑定保存失败");}finally{saving.value=false;}}
watch(selectedUsage,syncBindings); onMounted(load);
</script>

<template><div class="aiops-page" :class="{loading}"><section class="aiops-page-head"><div><span>AIOps · 模型网关</span><h1>模型与用途配置</h1><p>统一管理模型供应商、可用模型和各业务用途的绑定关系，密钥仅在后端保存。</p></div><div class="aiops-head-actions"><button class="btn btn-secondary" @click="load"><RefreshCw :size="15"/>刷新</button><button class="btn btn-primary" @click="editProvider()"><Plus :size="15"/>新增供应商</button><button class="btn btn-primary" :disabled="!providers.length" @click="editModel()"><Plus :size="15"/>新增模型</button></div></section><AiopsModuleTabs/><div v-if="error" class="aiops-notice error">{{error}}</div><div v-if="notice" class="aiops-notice success">{{notice}}</div>
<form v-if="providerEditor" class="card aiops-editor aiops-editor-wide" @submit.prevent="saveProvider"><label><span>名称</span><input v-model="providerForm.name" required/></label><label><span>Base URL</span><input v-model="providerForm.base_url" required placeholder="https://api.example.com/v1"/></label><label><span>API Key（留空不修改）</span><input v-model="providerForm.api_key" type="password" autocomplete="new-password"/></label><label><span>密钥环境变量</span><input v-model="providerForm.api_key_env"/></label><label><span>超时秒数</span><input v-model.number="providerForm.timeout_seconds" type="number" min="3" max="600"/></label><label><span>备注</span><input v-model="providerForm.remark"/></label><div class="aiops-editor-actions"><button type="button" class="btn btn-secondary" @click="providerEditor=false">取消</button><button class="btn btn-primary" :disabled="saving"><Save :size="14"/>保存供应商</button></div></form>
<form v-if="modelEditor" class="card aiops-editor aiops-editor-wide" @submit.prevent="saveModel"><label><span>供应商</span><select v-model="modelForm.provider_id" required><option v-for="p in providers" :key="p.id" :value="String(p.id)">{{p.name}}</option></select></label><label><span>模型 ID</span><input v-model="modelForm.model_id" required/></label><label><span>显示名称</span><input v-model="modelForm.display_name"/></label><label><span>端点类型</span><select v-model="modelForm.endpoint_type"><option value="chat">Chat</option><option value="embeddings">Embedding</option><option value="rerank">Rerank</option></select></label><label><span>输入类型（逗号分隔）</span><input v-model="modelForm.input_types"/></label><label><span>上下文 Token</span><input v-model="modelForm.max_context_tokens" type="number"/></label><label><span>最大输出 Token</span><input v-model="modelForm.max_output_tokens" type="number"/></label><label><span>备注</span><input v-model="modelForm.remark"/></label><label class="aiops-check"><input v-model="modelForm.supports_tools" type="checkbox"/>支持 Tools</label><label class="aiops-check"><input v-model="modelForm.supports_streaming" type="checkbox"/>支持流式</label><div class="aiops-editor-actions"><button type="button" class="btn btn-secondary" @click="modelEditor=false">取消</button><button class="btn btn-primary" :disabled="saving"><Save :size="14"/>保存模型</button></div></form>
<section class="aiops-model-layout"><article class="card aiops-model-section"><header><div><Cpu :size="20"/><span><h2>模型供应商</h2><p>{{providers.length}} 个接入点</p></span></div></header><div class="aiops-provider-list"><div v-for="p in providers" :key="p.id"><span class="aiops-status-dot" :class="p.status==='ok'?'ok':p.enabled?'warning':'muted'"></span><div><strong>{{p.name}}</strong><small>{{p.base_url}} · {{p.api_key_masked||p.api_key_env||'未配置密钥'}}</small></div><em>{{p.model_count||0}} 模型</em><button class="btn btn-secondary" :disabled="busy===`p${p.id}`" @click="refreshProvider(p)"><RotateCw :size="14"/>同步</button><button class="btn btn-secondary" @click="editProvider(p)"><Pencil :size="14"/></button><button class="btn btn-danger-ghost" @click="deleteProvider(p)"><Trash2 :size="14"/></button></div><div v-if="!providers.length&&!loading" class="aiops-empty"><strong>尚未配置供应商</strong></div></div></article>
<article class="card aiops-model-section aiops-binding-editor"><header><div><TestTube2 :size="20"/><span><h2>用途绑定</h2><p>按优先级依次尝试模型</p></span></div></header><div class="aiops-binding-controls"><select v-model="selectedUsage"><option v-for="u in usageKeys" :key="u.key" :value="u.key">{{u.label}}</option></select><button class="btn btn-secondary" @click="addBinding"><Plus :size="14"/>添加</button></div><div class="aiops-binding-draft"><div v-for="(b,i) in bindingDraft" :key="i"><select v-model="b.model_pk"><option v-for="m in chatModels" :key="m.id" :value="String(m.id)">{{m.provider_name}} / {{m.display_name||m.model_id}}</option></select><input v-model.number="b.priority" type="number" min="1" title="优先级"/><input v-model="b.purpose_note" placeholder="用途说明"/><button class="btn btn-danger-ghost" @click="bindingDraft.splice(i,1)"><Trash2 :size="14"/></button></div><div v-if="!bindingDraft.length" class="aiops-empty"><strong>当前用途尚未绑定模型</strong></div></div><footer><button class="btn btn-primary" :disabled="saving" @click="saveBindings"><Save :size="14"/>保存绑定</button></footer></article></section>
<section class="card aiops-table-card"><div class="table-scroll"><table class="data-table aiops-table"><thead><tr><th>模型</th><th>供应商</th><th>端点类型</th><th>能力</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="m in models" :key="m.id"><td><strong>{{m.display_name||m.model_id}}</strong><small>{{m.model_id}}</small></td><td>{{m.provider_name||'-'}}</td><td>{{m.endpoint_type||'-'}}</td><td><div class="aiops-tags"><span v-if="m.supports_tools">Tools</span><span v-if="m.supports_streaming">Streaming</span><span v-for="type in m.input_types" :key="type">{{type}}</span></div></td><td><span class="aiops-state-pill" :class="m.status==='ok'?'ok':'muted'">{{m.enabled?(m.status||'未测试'):'已停用'}}</span></td><td><div class="aiops-head-actions"><button class="btn btn-secondary" :disabled="busy===`m${m.id}`" @click="testModel(m)"><TestTube2 :size="14"/>测试</button><button class="btn btn-secondary" @click="editModel(m)"><Pencil :size="14"/>编辑</button><button class="btn btn-danger-ghost" @click="deleteModel(m)"><Trash2 :size="14"/>删除</button></div></td></tr></tbody></table></div><div v-if="!models.length&&!loading" class="aiops-empty"><strong>没有可用模型</strong></div></section></div></template>
