<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { Building2, Link2, Plus, RadioTower } from "lucide-vue-next";
import OrganizationTree, { type OrganizationTreeNode } from "../components/OrganizationTree.vue";
import { api } from "../services/api";

const items=ref<any[]>([]),mappings=ref<any[]>([]),selectedId=ref<string|number>("");
const loading=ref(false),saving=ref(false),error=ref(""),message=ref(""),formOpen=ref(false),editingId=ref<number|null>(null);
const isSuperAdmin=ref(false);
const form=ref({name:"",node_type:"region",region_code:"",parent_id:"",sort_order:0});
const selected=computed(()=>items.value.find(i=>String(i.id)===String(selectedId.value))||null);
const selectedRegion=computed(()=>selected.value?.region_code||"");
const tree=computed<OrganizationTreeNode[]>(()=>{const byParent=new Map<string,any[]>();for(const item of items.value){const key=String(item.parent_id||"");if(!byParent.has(key))byParent.set(key,[]);byParent.get(key)!.push(item);}const build=(parent:string):OrganizationTreeNode[]=>(byParent.get(parent)||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(i=>({id:i.id,label:i.name,count:Number(i.device_count||0),meta:i,children:build(String(i.id))}));return build("");});
async function load(){loading.value=true;error.value="";try{const [orgData,meData]=await Promise.all([api<any>("/device-orgs"),api<any>("/auth/me")]);items.value=orgData.items||[];isSuperAdmin.value=(meData.user||meData)?.role_code==="super_admin";if(!selected.value)selectedId.value=items.value.find(i=>i.node_type==="region")?.id||items.value[0]?.id||"";if(isSuperAdmin.value){const mapData=await api<any>("/organization-mappings");mappings.value=(mapData.items||[]).map((i:any)=>({...i,regions:[...(i.regions||[])]}));}else{mappings.value=[];}}catch(e){error.value=e instanceof Error?e.message:"设备组织加载失败";}finally{loading.value=false;}}
function openCreate(parent:any=null){const row=parent||selected.value;editingId.value=null;form.value={name:"",node_type:row?.node_type==="region"?"room":"region",region_code:"",parent_id:row?.node_type==="region"?String(row.id):"",sort_order:0};formOpen.value=true;}
function openEdit(row:any=selected.value){if(!row)return;editingId.value=row.id;form.value={name:row.name,node_type:row.node_type,region_code:row.region_code,parent_id:row.parent_id||"",sort_order:row.sort_order||0};formOpen.value=true;}
async function save(){saving.value=true;error.value="";try{await api(editingId.value?`/device-orgs/${editingId.value}`:"/device-orgs",{method:editingId.value?"PUT":"POST",body:JSON.stringify(form.value)});message.value=editingId.value?"设备组织已更新":"设备组织已创建";formOpen.value=false;await load();}catch(e){error.value=e instanceof Error?e.message:"设备组织保存失败";}finally{saving.value=false;}}
async function removeOrg(node:OrganizationTreeNode|null){const row=(node?.meta as any)||selected.value;if(!row)return;if(!window.confirm(`确认删除设备组织“${row.name}”？`))return;try{await api(`/device-orgs/${row.id}`,{method:"DELETE"});message.value="设备组织已删除";selectedId.value="";load();}catch(e){error.value=e instanceof Error?e.message:"删除失败";}}
async function dropOrg(source:OrganizationTreeNode,target:OrganizationTreeNode){const s=source.meta as any,t=target.meta as any;if(s?.node_type!=="room"||t?.node_type!=="region"){error.value="只能把机房拖拽到区域组织下";return;}try{await api(`/device-orgs/${source.id}/move`,{method:"POST",body:JSON.stringify({parent_id:target.id,sort_order:s.sort_order||0})});message.value=`已将“${s.name}”移动到“${t.name}”`;load();}catch(e){error.value=e instanceof Error?e.message:"移动失败";}}
async function move(direction:"up"|"down",node:OrganizationTreeNode|null){const row=(node?.meta as any)||selected.value;if(!row)return;try{await api(`/device-orgs/${row.id}/move`,{method:"POST",body:JSON.stringify({parent_id:row.parent_id,sort_order:Number(row.sort_order||0)+(direction==="up"?-10:10)})});message.value="设备组织排序已调整";load();}catch(e){error.value=e instanceof Error?e.message:"排序失败";}}
async function saveMapping(row:any){saving.value=true;try{await api(`/organization-mappings/${row.user_org_id}`,{method:"PUT",body:JSON.stringify({regions:row.regions})});message.value=`${row.user_org_name} 的设备范围已保存`;}catch(e){error.value=e instanceof Error?e.message:"映射保存失败";}finally{saving.value=false;}}
function toggleRegion(row:any,checked:boolean){const code=selectedRegion.value;if(!code)return;const next=new Set(row.regions||[]);checked?next.add(code):next.delete(code);row.regions=[...next];saveMapping(row);}
onMounted(load);
</script>

<template><div class="manage-page">
  <section class="manage-hero card card-pad"><div><div class="eyebrow">设备域与用户域关联</div><h1>设备组织管理</h1><p>设备组织固定为“区域 → 机房”两层；区域级映射决定用户能够查看的设备和业务数据。</p></div><button class="btn btn-primary" @click="openCreate()"><Plus :size="17"/>新增设备组织</button></section>
  <div v-if="error" class="quality-message error">{{error}}</div><div v-if="message" class="quality-message success">{{message}}</div>
  <div class="split-manage-layout">
    <OrganizationTree :nodes="tree" :selected-id="selectedId" title="设备组织" subtitle="区域 / 机房，可拖拽机房" :total-label="`${items.filter(i=>i.node_type==='region').length} 个区域`" editable draggable @select="selectedId=$event?.id||''" @add="openCreate(($event as any)?.meta)" @remove="removeOrg" @move="move" @drop="dropOrg" />
    <main class="split-manage-main">
      <section v-if="selected" class="card org-detail-card"><header><div class="org-detail-icon"><RadioTower v-if="selected.node_type==='region'" :size="24"/><Building2 v-else :size="24"/></div><div><span>{{selected.node_type==='region'?'设备区域':'机房'}}</span><h2>{{selected.name}}</h2><p>区域编码 {{selected.region_code}} · {{selected.device_count||0}} 台设备</p></div></header><div class="org-detail-actions"><button class="btn btn-primary" @click="openCreate(selected)">{{selected.node_type==='region'?'新增机房':'新增区域'}}</button><button class="btn btn-secondary" @click="openEdit(selected)">编辑</button></div></section>
      <section v-else class="card org-welcome"><RadioTower :size="36"/><h2>{{loading?'正在加载设备组织':'暂无可访问的设备组织'}}</h2><p>{{loading?'首次进入后将直接选中可访问区域。':'请联系系统管理员检查用户组织与设备区域映射。'}}</p></section>
      <section v-if="isSuperAdmin&&selectedRegion" class="card region-access-card"><header><div><h2><Link2 :size="19"/>可访问“{{items.find(i=>i.node_type==='region'&&i.region_code===selectedRegion)?.name}}”的用户组织</h2><p>勾选后立即保存；三级用户组织自动继承其二级组织范围。</p></div></header><div class="region-access-grid"><label v-for="row in mappings" :key="row.user_org_id"><input type="checkbox" :checked="row.regions.includes(selectedRegion)" :disabled="saving" @change="toggleRegion(row,($event.target as HTMLInputElement).checked)"/><span>{{row.user_org_name}}</span></label></div></section>
    </main>
  </div>
  <div v-if="formOpen" class="quality-detail-mask" @click.self="formOpen=false"><section class="quality-detail-panel compact-form-panel card"><header class="detail-panel-head"><div><span>{{editingId?'编辑设备组织':'新增设备组织'}}</span><h2>{{form.name||'设备组织信息'}}</h2></div><button class="round-icon-btn" @click="formOpen=false">×</button></header><div class="device-form-grid"><div class="field"><label>组织类型</label><select v-model="form.node_type" class="select" :disabled="!!editingId"><option value="region">区域</option><option value="room">机房</option></select></div><div class="field"><label>组织名称</label><input v-model="form.name" class="input"/></div><div v-if="form.node_type==='region'" class="field"><label>区域编码</label><input v-model="form.region_code" class="input" :disabled="!!editingId" placeholder="如 chengxi"/></div><div v-else class="field"><label>所属区域</label><select v-model="form.parent_id" class="select"><option v-for="r in items.filter(i=>i.node_type==='region')" :key="r.id" :value="r.id">{{r.name}}</option></select></div><div class="field"><label>排序值</label><input v-model.number="form.sort_order" type="number" class="input"/></div></div><footer class="device-form-actions"><button class="btn btn-secondary" @click="formOpen=false">取消</button><button class="btn btn-primary" :disabled="saving" @click="save">保存设备组织</button></footer></section></div>
</div></template>
