<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { Check, LockKeyhole, Save, ShieldCheck, Smartphone, Monitor } from "lucide-vue-next";
import { adminApi } from "../services/api";
const menus=ref<any[]>([]),loading=ref(false),savingId=ref<number|null>(null),error=ref(""),message=ref(""),scope=ref<"web"|"miniapp">("web");
const webLabels:Record<string,[string,string]>={
  "netops.dashboard":["统一驾驶舱","总览"],"netops.onu_search":["单台 ONU 查询","FTTH 网络管理"],"netops.quality":["ONU 质差管理","FTTH 网络管理"],"netops.performance":["OLT 性能看板","FTTH 网络管理"],"netops.collector":["采集监控","FTTH 网络管理"],"netops.devices":["OLT 设备管理","FTTH 网络管理"],"netops.boss_users":["BOSS 用户管理","FTTH 网络管理"],"netops.hfc":["CM MAC 查询","HFC 网络管理"],"netops.cmts_devices":["CMTS 设备管理","HFC 网络管理"],"netops.radius":["Radius 管理系统","Radius 管理"],"netops.aiops":["AIOps 智能运维","智能运维"],"netops.ai_assistant":["AI 问答","智能运维"],"netops.aiops_knowledge":["知识库","智能运维"],"netops.aiops_admin":["AIOps 系统管理","系统管理"],"netops.settings":["系统配置","系统管理"],"netops.users":["用户管理","系统管理"],"netops.orgs":["用户组织管理","系统管理"],"netops.device_orgs":["设备组织管理","系统管理"],"netops.permissions":["权限管理","系统管理"]
};
const roles=[{code:"normal_user",name:"普通用户",desc:"业务查询和日常操作"},{code:"org_admin",name:"组织管理员",desc:"管理所属组织及下级"},{code:"super_admin",name:"系统管理员",desc:"全平台配置与权限管理"}];
const visible=computed(()=>menus.value.filter(m=>scope.value==="web"?String(m.menu_key).startsWith("netops."):!String(m.menu_key).startsWith("netops.")));
const groups=computed(()=>{const result=new Map<string,any[]>();for(const menu of visible.value){const key=menu.group_name||"其他";if(!result.has(key))result.set(key,[]);result.get(key)!.push(menu);}return Array.from(result,([name,items])=>({name,items}));});
async function load(){loading.value=true;error.value="";try{const data=await adminApi<any>("/menus");menus.value=(data.items||[]).map((m:any)=>{const fallback=webLabels[m.menu_key];return {...m,name:(m.name&&!String(m.name).includes("?"))?m.name:(fallback?.[0]||m.menu_key),group_name:(m.group_name&&!String(m.group_name).includes("?"))?m.group_name:(fallback?.[1]||"其他")};});}catch(e){error.value=e instanceof Error?e.message:"权限配置加载失败";}finally{loading.value=false;}}
async function save(menu:any){savingId.value=menu.id;error.value="";try{await adminApi(`/menus/${menu.id}`,{method:"PUT",body:JSON.stringify(menu)});message.value=`${menu.name} 权限已更新`;}catch(e){error.value=e instanceof Error?e.message:"权限保存失败";}finally{savingId.value=null;}}
async function toggle(menu:any){menu.enabled=!menu.enabled;try{await adminApi(`/menus/${menu.id}/${menu.enabled?'enable':'disable'}`,{method:"POST"});message.value=`${menu.name} 已${menu.enabled?'启用':'停用'}`;}catch(e){menu.enabled=!menu.enabled;error.value=e instanceof Error?e.message:"状态更新失败";}}
onMounted(load);
</script>
<template><div class="manage-page">
  <section class="manage-hero card card-pad"><div><div class="eyebrow">角色与功能边界</div><h1>权限管理</h1><p>统一维护 Web 平台和原有小程序菜单权限；最低角色配置会实际控制菜单可见性。</p></div><div class="permission-hero-icon"><ShieldCheck :size="28"/></div></section>
  <div v-if="error" class="quality-message error">{{error}}</div><div v-if="message" class="quality-message success">{{message}}</div>
  <section class="permission-role-strip"><article v-for="(role,index) in roles" :key="role.code" class="card"><div class="role-order">{{index+1}}</div><div><h3>{{role.name}}</h3><p>{{role.desc}}</p></div><Check :size="18"/></article></section>
  <section class="card permission-scope-tabs"><button :class="{active:scope==='web'}" @click="scope='web'"><Monitor :size="18"/><span><strong>Web 平台</strong><em>{{menus.filter(m=>String(m.menu_key).startsWith('netops.')).length}} 项功能</em></span></button><button :class="{active:scope==='miniapp'}" @click="scope='miniapp'"><Smartphone :size="18"/><span><strong>小程序</strong><em>{{menus.filter(m=>!String(m.menu_key).startsWith('netops.')).length}} 项原有功能</em></span></button></section>
  <section class="card permission-matrix" :class="{loading}"><header><div><h2>{{scope==='web'?'Web 功能访问矩阵':'小程序功能访问矩阵'}}</h2><p>最低角色遵循：普通用户 ＜ 组织管理员 ＜ 系统管理员</p></div><LockKeyhole :size="22"/></header><div v-for="group in groups" :key="group.name" class="permission-group"><h3>{{group.name}}</h3><article v-for="menu in group.items" :key="menu.id" class="permission-row" :class="{disabled:!menu.enabled}"><div class="permission-menu-name"><strong>{{menu.name}}</strong><span>{{menu.path||'无页面地址'}} · {{menu.menu_key}}</span></div><label><span>最低角色</span><select v-model="menu.min_role" class="select"><option v-for="r in roles" :key="r.code" :value="r.code">{{r.name}}</option></select></label><label><span>用户类型</span><select v-model="menu.user_type" class="select"><option value="all">全部类型</option><option value="internal">内部用户</option><option value="external">外部用户</option><option value="system">系统账号</option></select></label><label class="permission-enabled"><input :checked="menu.enabled" type="checkbox" @change="toggle(menu)"/><span>{{menu.enabled?'已启用':'已停用'}}</span></label><button class="btn btn-secondary" :disabled="savingId===menu.id" @click="save(menu)"><Save :size="15"/>{{savingId===menu.id?'保存中':'保存'}}</button></article></div></section>
</div></template>
