<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { ArrowDownAZ, Plus, Search, SlidersHorizontal, Trash2 } from "lucide-vue-next";
import EmptyState from "../components/EmptyState.vue";
import OrganizationTree, { type OrganizationTreeNode } from "../components/OrganizationTree.vue";
import StatusTag from "../components/StatusTag.vue";
import { adminApi, api } from "../services/api";

const rows=ref<any[]>([]), total=ref(0), page=ref(1), size=ref(20), loading=ref(false), saving=ref(false), deleting=ref(false);
const error=ref(""), message=ref(""), formError=ref(""), options=ref<any>({orgs:[],role_codes:[],user_types:[],statuses:[],oss_bind_statuses:[]});
const orgItems=ref<any[]>([]), orgTotal=ref(0), unassignedCount=ref(0), selectedOrg=ref<string|number>("");
const filters=ref({keyword:"",role_code:"",status:"",user_type:"",oss_bind_status:""});
const sort=ref("name_asc"), formOpen=ref(false), editingId=ref<number|null>(null), form=ref(emptyForm());
const currentUserId=ref<number|null>(null), deleteTarget=ref<any|null>(null);
function emptyForm(){return {real_name:"",mobile:"",oa_username:"",oss_account:"",org_id:"",manage_org_id:"",role_code:"normal_user",user_type:"internal",status:"active"};}
const pages=computed(()=>Math.max(1,Math.ceil(total.value/size.value)));
function roleLabel(v:string){return ({super_admin:"系统管理员",org_admin:"组织管理员",normal_user:"普通用户"} as Record<string,string>)[v]||v;}
function typeLabel(v:string){return ({internal:"内部用户",external:"外部用户",system:"系统账号"} as Record<string,string>)[v]||v;}
function statusLabel(v:string){return ({active:"正常",disabled:"停用",pending:"待启用"} as Record<string,string>)[v]||v;}
function ossLabel(v:string){return ({bound:"已绑定",unbound:"未绑定",invalid:"异常"} as Record<string,string>)[v]||v||"未绑定";}
const orgTree=computed<OrganizationTreeNode[]>(()=>{const byParent=new Map<string,any[]>();for(const item of orgItems.value){const key=String(item.parent_id||"");if(!byParent.has(key))byParent.set(key,[]);byParent.get(key)!.push(item);}const build=(parent:string):OrganizationTreeNode[]=>(byParent.get(parent)||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(item=>({id:item.id,label:item.name,count:item.user_count,meta:item,children:build(String(item.id))}));const roots=build("");if(unassignedCount.value>0)roots.push({id:"unassigned",label:"未分配组织",count:unassignedCount.value,children:[]});return roots;});
function applyOrganizationData(data:any){orgItems.value=data.items||[];orgTotal.value=Number(data.total||0);unassignedCount.value=Number(data.unassigned_count||0);}
async function loadOrganizations(){const data=await api<any>("/access/orgs/tree");applyOrganizationData(data);}
function query(){const [sortBy,sortOrder]=sort.value.split("_");const p=new URLSearchParams({page:String(page.value),page_size:String(size.value),sort_by:sortBy,sort_order:sortOrder});if(selectedOrg.value)p.set("org_id",String(selectedOrg.value));for(const [k,v] of Object.entries(filters.value))if(v)p.set(k,v);return p.toString();}
async function load(){loading.value=true;error.value="";try{const data=await api<any>(`/access/users?${query()}`);rows.value=data.items||[];total.value=data.total||0;}catch(e){error.value=e instanceof Error?e.message:"用户加载失败";}finally{loading.value=false;}}
function search(){page.value=1;load();} function reset(){filters.value={keyword:"",role_code:"",status:"",user_type:"",oss_bind_status:""};selectedOrg.value="";sort.value="name_asc";search();} function gotoPage(n:number){page.value=Math.max(1,Math.min(pages.value,n));load();}
function chooseOrg(node:OrganizationTreeNode|null){selectedOrg.value=node?.id||"";search();}
function openCreate(){editingId.value=null;formError.value="";form.value={...emptyForm(),org_id:selectedOrg.value?String(selectedOrg.value):""};formOpen.value=true;} function openEdit(row:any){editingId.value=row.id;formError.value="";form.value={...emptyForm(),...row,org_id:row.org_id||"",manage_org_id:row.manage_org_id||""};syncManageOrganization();formOpen.value=true;}
function syncManageOrganization(){if(form.value.role_code!=="org_admin"){form.value.manage_org_id="";return;}const assigned=options.value.orgs.find((item:any)=>String(item.id)===String(form.value.org_id));const managed=options.value.orgs.find((item:any)=>String(item.id)===String(form.value.manage_org_id));if(!assigned){form.value.manage_org_id="";return;}const managedInScope=managed&&(managed.id===assigned.id||String(managed.path||"").startsWith(String(assigned.path||"/invalid/")));if(!managedInScope)form.value.manage_org_id=assigned.id;}
function canChooseManagedOrganization(candidate:any){const assigned=options.value.orgs.find((item:any)=>String(item.id)===String(form.value.org_id));return !!assigned&&(String(candidate.id)===String(assigned.id)||String(candidate.path||"").startsWith(String(assigned.path||"/invalid/")));}
function friendlyFormError(value:string){const messages:Record<string,string>={"manage_org_id must be the assigned organization or one of its children":"管理组织只能选择所属组织或其下级组织","org_admin requires org_id":"组织管理员必须选择所属组织","mobile is invalid":"请输入正确的手机号","mobile already exists":"该手机号已被其他用户使用","oss_account already exists":"该 OSS 账号已被其他用户使用","permission denied":"当前账号没有权限执行此操作"};return messages[value]||value||"保存用户失败，请检查填写内容";}
async function save(){saving.value=true;formError.value="";try{const path=editingId.value?`/users/${editingId.value}`:"/users";const data=await adminApi<any>(path,{method:editingId.value?"PUT":"POST",body:JSON.stringify(form.value)});message.value=data.initial_password?`用户已创建，初始密码：${data.initial_password}`:"用户信息已更新";formOpen.value=false;await Promise.all([load(),loadOrganizations()]);}catch(e){formError.value=friendlyFormError(e instanceof Error?e.message:"");}finally{saving.value=false;}}
async function action(row:any,name:"enable"|"disable"|"reset-password"){try{const data=await adminApi<any>(`/users/${row.id}/${name}`,{method:"POST"});message.value=data.initial_password?`密码已重置为：${data.initial_password}`:(name==="enable"?"用户已启用":"用户已停用");load();}catch(e){error.value=e instanceof Error?e.message:"操作失败";}}
function askDelete(row:any){error.value="";message.value="";deleteTarget.value=row;}
async function confirmDelete(){if(!deleteTarget.value)return;deleting.value=true;error.value="";try{const name=deleteTarget.value.real_name||deleteTarget.value.mobile;await api<any>(`/access/users/${deleteTarget.value.id}`,{method:"DELETE"});message.value=`用户“${name}”已删除`;deleteTarget.value=null;if(rows.value.length===1&&page.value>1)page.value-=1;await Promise.all([load(),loadOrganizations()]);}catch(e){error.value=e instanceof Error?e.message:"删除用户失败";}finally{deleting.value=false;}}
onMounted(async()=>{try{const [opts,orgs,meData]=await Promise.all([api<any>("/access/user-options"),api<any>("/access/orgs/tree"),api<any>("/auth/me")]);options.value=opts;applyOrganizationData(orgs);currentUserId.value=Number(meData.user?.id||meData.id||0)||null;}catch(e){error.value=e instanceof Error?e.message:"没有用户管理权限";}load();});
</script>

<template><div class="manage-page">
  <section class="manage-hero card card-pad"><div><div class="eyebrow">账号与数据权限</div><h1>用户管理</h1><p>先选择组织，再按账号、角色、OSS 绑定和状态定位用户。</p></div><button class="btn btn-primary" @click="openCreate"><Plus :size="17"/>新增用户</button></section>
  <div v-if="error" class="quality-message error">{{error}}</div><div v-if="message" class="quality-message success">{{message}}</div>
  <div class="split-manage-layout">
    <OrganizationTree :nodes="orgTree" :selected-id="selectedOrg" title="用户组织" subtitle="公司 / 区域 / 班组" :total-label="`${orgTotal} 人`" @select="chooseOrg" />
    <main class="split-manage-main">
      <section class="card manage-filter"><div class="filter-caption"><SlidersHorizontal :size="16"/><strong>筛选条件</strong><button @click="reset">重置</button></div><div class="manage-filter-grid user-filter-grid"><label class="filter-search"><Search :size="15"/><input v-model="filters.keyword" placeholder="姓名 / 手机 / OA / OSS 账号" @keydown.enter="search"/></label><select v-model="filters.role_code" class="select"><option value="">全部角色</option><option v-for="v in options.role_codes" :key="v" :value="v">{{roleLabel(v)}}</option></select><select v-model="filters.user_type" class="select"><option value="">全部类型</option><option v-for="v in options.user_types" :key="v" :value="v">{{typeLabel(v)}}</option></select><select v-model="filters.status" class="select"><option value="">全部状态</option><option v-for="v in options.statuses" :key="v" :value="v">{{statusLabel(v)}}</option></select><select v-model="filters.oss_bind_status" class="select"><option value="">全部 OSS 状态</option><option v-for="v in options.oss_bind_statuses" :key="v" :value="v">{{ossLabel(v)}}</option></select><button class="btn btn-primary" @click="search">查询</button></div></section>
      <section class="card table-card manage-table-card" :class="{loading}"><div class="table-head"><div><h2>组织用户</h2><p>共 {{total}} 个账号</p></div><div class="table-head-actions"><ArrowDownAZ :size="16"/><select v-model="sort" class="select tiny-select" @change="search"><option value="name_asc">用户名升序</option><option value="name_desc">用户名降序</option><option value="role_asc">角色升序</option><option value="role_desc">角色降序</option></select><select v-model.number="size" class="select tiny-select" @change="gotoPage(1)"><option :value="20">20 条/页</option><option :value="50">50 条/页</option></select></div></div><EmptyState v-if="!loading&&!rows.length" title="暂无用户" description="当前组织和筛选条件下没有用户。"/><div v-else class="table-wrap"><table class="data-table manage-data-table"><thead><tr><th>用户</th><th>登录账号</th><th>所属组织</th><th>角色 / 管理范围</th><th>OSS</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td><strong>{{r.real_name||'-'}}</strong><div class="muted">{{typeLabel(r.user_type)}} · ID {{r.id}}</div></td><td>{{r.oa_username||'-'}}<div class="muted">{{r.mobile||'-'}}</div></td><td>{{r.org_name||'-'}}</td><td><span class="role-badge" :class="r.role_code">{{roleLabel(r.role_code)}}</span><div class="muted">{{r.manage_org_name||'无额外管理范围'}}</div></td><td>{{r.oss_account||'-'}}<div class="muted">{{ossLabel(r.oss_bind_status)}}</div></td><td><StatusTag :value="statusLabel(r.status)"/><div class="muted">密码 {{r.password_status}}</div></td><td><div class="row-actions"><button class="outline-action" @click="openEdit(r)">编辑</button><button class="outline-action" @click="action(r,'reset-password')">重置密码</button><button class="outline-action" @click="action(r,r.status==='active'?'disable':'enable')">{{r.status==='active'?'停用':'启用'}}</button><button v-if="r.id!==currentUserId" class="outline-action danger-action" @click="askDelete(r)"><Trash2 :size="14"/>删除</button></div></td></tr></tbody></table></div><div v-if="total" class="pagination modern-pagination"><button class="btn btn-secondary" :disabled="page<=1" @click="gotoPage(page-1)">‹</button><span>第 {{page}} / {{pages}} 页</span><button class="btn btn-secondary" :disabled="page>=pages" @click="gotoPage(page+1)">›</button></div></section>
    </main>
  </div>
  <div v-if="formOpen" class="quality-detail-mask" @click.self="formOpen=false"><section class="quality-detail-panel device-form-panel card"><header class="detail-panel-head"><div><span>{{editingId?'编辑用户':'新增用户'}}</span><h2>{{form.real_name||'用户资料与权限'}}</h2><p>OA 用户名、手机号和姓名来自统一账号主数据；OSS 仅用于智能装维等特殊能力。</p></div><button class="round-icon-btn" @click="formOpen=false">×</button></header><div v-if="formError" class="form-inline-error">{{formError}}</div><div class="device-form-grid"><div class="field"><label>姓名</label><input v-model="form.real_name" class="input"/></div><div class="field"><label>手机号</label><input v-model="form.mobile" class="input"/></div><div class="field"><label>OA 用户名</label><input v-model="form.oa_username" class="input"/></div><div class="field"><label>用户类型</label><select v-model="form.user_type" class="select"><option v-for="v in options.user_types" :key="v" :value="v">{{typeLabel(v)}}</option></select></div><div class="field"><label>所属组织</label><select v-model="form.org_id" class="select" @change="syncManageOrganization"><option value="">未分配</option><option v-for="o in options.orgs" :key="o.id" :value="o.id">{{o.display_name}}</option></select></div><div class="field"><label>角色</label><select v-model="form.role_code" class="select" @change="syncManageOrganization"><option v-for="v in options.role_codes" :key="v" :value="v">{{roleLabel(v)}}</option></select></div><div v-if="form.role_code==='org_admin'" class="field"><label>管理组织</label><select v-model="form.manage_org_id" class="select"><option v-for="o in options.orgs" :key="o.id" :value="o.id" :disabled="!canChooseManagedOrganization(o)">{{o.display_name}}</option></select></div><div class="field"><label>OSS 账号（按需绑定）</label><input v-model="form.oss_account" class="input"/></div><div class="field"><label>状态</label><select v-model="form.status" class="select"><option v-for="v in options.statuses" :key="v" :value="v">{{statusLabel(v)}}</option></select></div></div><footer class="device-form-actions"><button class="btn btn-secondary" @click="formOpen=false">取消</button><button class="btn btn-primary" :disabled="saving" @click="save">保存用户</button></footer></section></div>
  <div v-if="deleteTarget" class="quality-detail-mask" @click.self="deleteTarget=null"><section class="delete-confirm-panel card"><div class="delete-confirm-icon"><Trash2 :size="24"/></div><h2>确认删除用户？</h2><p>将永久删除 <strong>{{deleteTarget.real_name||deleteTarget.mobile}}</strong>（{{deleteTarget.mobile}}）。历史登录、操作和工单记录会保留，但无法恢复该账号。</p><footer><button class="btn btn-secondary" :disabled="deleting" @click="deleteTarget=null">取消</button><button class="btn btn-danger" :disabled="deleting" @click="confirmDelete">{{deleting?'正在删除…':'确认删除'}}</button></footer></section></div>
</div></template>
